spring.application.name=NurseQuiz
Server.port=9090
#spring.datasource.url=jdbc:postgresql://localhost:5432/NurseQuiz
spring.datasource.url=jdbc:postgresql://dpg-d7unhj5b910c73ep3ou0-a:5432/nursequiz
#spring.datasource.username=postgres
#spring.datasource.password=231303
spring.datasource.username=nursequiz_user
spring.datasource.password=BND1ZIQrn1JSJyIsHALQMta1y0u7dpDJ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pandeyankur804@gmail.com
spring.mail.password=gjoevwnhqvejiosw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
razorpay.key.id=rzp_test_9OwkUMPPNDnk7f
razorpay.key.secret=KKceRmRNtdJy1esM7D1A9Vyp
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.enabled=true




